# Default values for name-lookup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



webServer:
  replicaCount: 1
  service:
    port: 2433
    type: ClusterIP
  # container port
  port: 2433
  image:
    repository: ghcr.io/translatorsri/nameresolution
    tag: "change-docker-to-use-current-code"

dataUrl: "https://stars.renci.org/var/babel_outputs/2023may18/solr/snapshot.backup.tar.gz"
forceRun: false

busybox:
  image:
    repository: busybox
    tag: stable

# busybox:
#   image:
#     repository: busybox
#     tag: latest

solr:
  service:
    port: 8983
    type: ClusterIP
  # container port
  port: 8983
  heap_mem: "-Xms4000m -Xmx4000m"
  image:
    repository: solr
    tag: latest
  resources:
    requests:
      memory: "5Gi"
    limits:
      memory: "5Gi"
  # As of Babel 2023may18, we need 128G to store the
  # backup + uncompressed backup + Solr database
  # So 500Gi should be enough for the time being.
  storage: 500Gi

  initresources:
    requests:
      memory: 5Gi
      cpu: 1000m
    limits:
      memory: 10Gi
      cpu: 1000m

nameOverride: ""
fullnameOverride: ""

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  pathType: "ImplementationSpecific"
  host:
  class:

x_trapi:
  maturity:
    value: "maturity"
  location:
    value: "location"
